(PROGN
 (DEFPARAMETER I 17)
 (TAGBODY
  BOOMBER::START
   (UNLESS (< I 26) (GO BOOMBER::EXIT))
   (PUTPIXEL I 1 C)
   (INCF I)
   (GO BOOMBER::START)
  BOOMBER::EXIT
   (VALUES))
 (PROGN
  (DEFPARAMETER I 14)
  (TAGBODY
   BOOMBER::START
    (UNLESS (< I 17) (GO BOOMBER::EXIT))
    (PROGN (PUTPIXEL I 2 C) (PUTPIXEL 12 I + 2 C))
    (INCF I)
    (GO BOOMBER::START)
   BOOMBER::EXIT
    (VALUES)))
 (PUTPIXEL 12 3 C)
 (PUTPIXEL 13 3 C)
 (PUTPIXEL 29 3 C)
 (PUTPIXEL 30 3 C)
 (PUTPIXEL 11 4 C)
 (PUTPIXEL 31 4 C)
 (PUTPIXEL 10 5 C)
 (PUTPIXEL 32 5 C)
 (PUTPIXEL 9 6 C)
 (PUTPIXEL 33 6 C)
 (PUTPIXEL 8 7 C)
 (PUTPIXEL 34 7 C)
 (PUTPIXEL 7 8 C)
 (PUTPIXEL 35 8 C)
 (PUTPIXEL 7 9 C)
 (PUTPIXEL 35 9 C)
 (PROGN
  (DEFPARAMETER I 10)
  (TAGBODY
   BOOMBER::START
    (UNLESS (< I 35) (GO BOOMBER::EXIT))
    (PROGN (PUTPIXEL 6 I C) (PUTPIXEL 36 I C))
    (INCF I)
    (GO BOOMBER::START)
   BOOMBER::EXIT
    (VALUES)))
 (PUTPIXEL 7 35 C)
 (PUTPIXEL 14 35 C)
 (PUTPIXEL 21 35 C)
 (PUTPIXEL 28 35 C)
 (PUTPIXEL 35 35 C)
 (PUTPIXEL 7 36 C)
 (PUTPIXEL 13 36 C)
 (PUTPIXEL 15 36 C)
 (PUTPIXEL 20 36 C)
 (PUTPIXEL 22 36 C)
 (PUTPIXEL 27 36 C)
 (PUTPIXEL 29 36 C)
 (PUTPIXEL 35 36 C)
 (PUTPIXEL 8 37 C)
 (PUTPIXEL 13 37 C)
 (PUTPIXEL 15 37 C)
 (PUTPIXEL 20 37 C)
 (PUTPIXEL 22 37 C)
 (PUTPIXEL 27 37 C)
 (PUTPIXEL 29 37 C)
 (PUTPIXEL 34 37 C)
 (PUTPIXEL 8 38 C)
 (PUTPIXEL 12 38 C)
 (PUTPIXEL 16 38 C)
 (PUTPIXEL 19 38 C)
 (PUTPIXEL 23 38 C)
 (PUTPIXEL 26 38 C)
 (PUTPIXEL 30 38 C)
 (PUTPIXEL 34 38 C)
 (PUTPIXEL 9 39 C)
 (PUTPIXEL 12 39 C)
 (PUTPIXEL 16 39 C)
 (PUTPIXEL 19 39 C)
 (PUTPIXEL 23 39 C)
 (PUTPIXEL 26 39 C)
 (PUTPIXEL 30 39 C)
 (PUTPIXEL 33 39 C)
 (PROGN
  (DEFPARAMETER I 10)
  (TAGBODY
   BOOMBER::START
    (UNLESS (< I 12) (GO BOOMBER::EXIT))
    (PROGN
     (PUTPIXEL I 40 C)
     (PUTPIXEL 7 I + 40 C)
     (PUTPIXEL 14 I + 40 C)
     (PUTPIXEL 21 I + 40 C))
    (INCF I)
    (GO BOOMBER::START)
   BOOMBER::EXIT
    (VALUES)))
 (SETFILLSTYLE 1 C)
 (FLOODFILL 18 2 C)
 (PROGN
  (DEFPARAMETER I 9)
  (TAGBODY
   BOOMBER::START
    (UNLESS (< I 15) (GO BOOMBER::EXIT))
    (PROGN (PUTPIXEL I 12 0) (PUTPIXEL 19 I + 12 0))
    (INCF I)
    (GO BOOMBER::START)
   BOOMBER::EXIT
    (VALUES)))
 (PROGN
  (DEFPARAMETER I 8)
  (TAGBODY
   BOOMBER::START
    (UNLESS (< I 16) (GO BOOMBER::EXIT))
    (PROGN (PUTPIXEL I 13 0) (PUTPIXEL 18 I + 13 0))
    (INCF I)
    (GO BOOMBER::START)
   BOOMBER::EXIT
    (VALUES)))
 (PROGN
  (DEFPARAMETER I 14)
  (TAGBODY
   BOOMBER::START
    (UNLESS (< I 18) (GO BOOMBER::EXIT))
    (PROGN (PUTPIXEL I 14 0) (PUTPIXEL 11 I + 14 0))
    (INCF I)
    (GO BOOMBER::START)
   BOOMBER::EXIT
    (VALUES)))
 (PROGN
  (DEFPARAMETER I 16)
  (TAGBODY
   BOOMBER::START
    (UNLESS (< I 21) (GO BOOMBER::EXIT))
    (PROGN (PUTPIXEL I 15 0) (PUTPIXEL 6 I + 15 0))
    (INCF I)
    (GO BOOMBER::START)
   BOOMBER::EXIT
    (VALUES)))
 (PROGN
  (DEFPARAMETER I 13)
  (TAGBODY
   BOOMBER::START
    (UNLESS (< I 16) (GO BOOMBER::EXIT))
    (PROGN
     (PUTPIXEL I 16 0)
     (PUTPIXEL 4 I + 16 0)
     (PUTPIXEL 10 I + 16 0)
     (PUTPIXEL 14 I + 16 0))
    (INCF I)
    (GO BOOMBER::START)
   BOOMBER::EXIT
    (VALUES)))
 (PUTPIXEL 10 14 0)
 (PUTPIXEL 32 14 0)
 (PROGN
  (DEFPARAMETER I 15)
  (TAGBODY
   BOOMBER::START
    (UNLESS (< I 20) (GO BOOMBER::EXIT))
    (PROGN (PUTPIXEL 9 I 0) (PUTPIXEL 33 I 0))
    (INCF I)
    (GO BOOMBER::START)
   BOOMBER::EXIT
    (VALUES)))
 (PUTPIXEL 10 20 0)
 (PUTPIXEL 32 20 0)
 (PUTPIXEL 11 21 0)
 (PUTPIXEL 31 21 0)
 (PROGN
  (DEFPARAMETER I 12)
  (TAGBODY
   BOOMBER::START
    (UNLESS (< I 16) (GO BOOMBER::EXIT))
    (PROGN (PUTPIXEL I 22 0) (PUTPIXEL 15 I + 22 0))
    (INCF I)
    (GO BOOMBER::START)
   BOOMBER::EXIT
    (VALUES)))
 (PUTPIXEL 16 21 0)
 (PUTPIXEL 26 21 0)
 (PUTPIXEL 17 20 0)
 (PUTPIXEL 25 20 0)
 (PROGN
  (DEFPARAMETER I 17)
  (TAGBODY
   BOOMBER::START
    (UNLESS (< I 20) (GO BOOMBER::EXIT))
    (PROGN (PUTPIXEL 18 I 0) (PUTPIXEL 24 I 0))
    (INCF I)
    (GO BOOMBER::START)
   BOOMBER::EXIT
    (VALUES)))
 (SETFILLSTYLE 1 15)
 (FLOODFILL 11 15 0)
 (FLOODFILL 30 15 0)
 (PROGN
  (DEFPARAMETER I 17)
  (TAGBODY
   BOOMBER::START
    (UNLESS (< I 20) (GO BOOMBER::EXIT))
    (PROGN
     (PUTPIXEL 12 I 0)
     (PUTPIXEL 16 I 0)
     (PUTPIXEL 26 I 0)
     (PUTPIXEL 30 I 0))
    (INCF I)
    (GO BOOMBER::START)
   BOOMBER::EXIT
    (VALUES)))
 (PROGN
  (DEFPARAMETER I 13)
  (TAGBODY
   BOOMBER::START
    (UNLESS (< I 16) (GO BOOMBER::EXIT))
    (PROGN (PUTPIXEL I 20 0) (PUTPIXEL 14 I + 20 0))
    (INCF I)
    (GO BOOMBER::START)
   BOOMBER::EXIT
    (VALUES)))
 (SETFILLSTYLE 1 RED)
 (FLOODFILL 13 17 0)
 (FLOODFILL 27 17 0)
 (PUTPIXEL 9 23 0)
 (PUTPIXEL 33 23 0)
 (PROGN
  (DEFPARAMETER I 10)
  (TAGBODY
   BOOMBER::START
    (UNLESS (< I 13) (GO BOOMBER::EXIT))
    (PROGN (PUTPIXEL I 24 0) (PUTPIXEL 20 I + 24 0))
    (INCF I)
    (GO BOOMBER::START)
   BOOMBER::EXIT
    (VALUES)))
 (PROGN
  (DEFPARAMETER I 13)
  (TAGBODY
   BOOMBER::START
    (UNLESS (< I 18) (GO BOOMBER::EXIT))
    (PROGN (PUTPIXEL I 25 0) (PUTPIXEL 12 I + 25 0))
    (INCF I)
    (GO BOOMBER::START)
   BOOMBER::EXIT
    (VALUES)))
 (PROGN
  (DEFPARAMETER I 18)
  (TAGBODY
   BOOMBER::START
    (UNLESS (< I 25) (GO BOOMBER::EXIT))
    (PUTPIXEL I 26 0)
    (INCF I)
    (GO BOOMBER::START)
   BOOMBER::EXIT
    (VALUES)))
 (DEFPARAMETER J 0)
 (PROGN
  (PROGN (DEFPARAMETER J 25) (DEFPARAMETER I 11))
  (TAGBODY
   BOOMBER::START
    (UNLESS (< J 31) (GO BOOMBER::EXIT))
    (PUTPIXEL I J 0)
    (PROGN (INCF I) (INCF J))
    (GO BOOMBER::START)
   BOOMBER::EXIT
    (VALUES)))
 (PROGN
  (PROGN (DEFPARAMETER J 25) (DEFPARAMETER I 31))
  (TAGBODY
   BOOMBER::START
    (UNLESS (< J 31) (GO BOOMBER::EXIT))
    (PUTPIXEL I J 0)
    (PROGN (DECF I) (INCF J))
    (GO BOOMBER::START)
   BOOMBER::EXIT
    (VALUES)))
 (PUTPIXEL 17 30 0)
 (PUTPIXEL 25 30 0)
 (PROGN
  (DEFPARAMETER I 18)
  (TAGBODY
   BOOMBER::START
    (UNLESS (< I 25) (GO BOOMBER::EXIT))
    (PUTPIXEL I 31 0)
    (INCF I)
    (GO BOOMBER::START)
   BOOMBER::EXIT
    (VALUES)))
 (SETFILLSTYLE 1 15)
 (FLOODFILL 19 28 0)
 (PROGN
  (DEFPARAMETER I 26)
  (TAGBODY
   BOOMBER::START
    (UNLESS (< I 30) (GO BOOMBER::EXIT))
    (PROGN (PUTPIXEL 16 I 0) (PUTPIXEL 26 I 0))
    (INCF I)
    (GO BOOMBER::START)
   BOOMBER::EXIT
    (VALUES)))
 (PROGN
  (DEFPARAMETER I 27)
  (TAGBODY
   BOOMBER::START
    (UNLESS (< I 31) (GO BOOMBER::EXIT))
    (PUTPIXEL 21 I 0)
    (INCF I)
    (GO BOOMBER::START)
   BOOMBER::EXIT
    (VALUES)))
 (DEFPARAMETER SIZE (IMAGESIZE 1 1 40 40))
 (DEFPARAMETER PTR (MALLOC SIZE))
 (GETIMAGE 1 1 40 40 PTR)
 (PUTIMAGE 1 1 PTR XOR_PUT))